export const GAMES = [
  {id: "red-blue", label: "Red / Blue"},
  {id: "yellow", label: "Yellow"},
  {id: "gold-silver", label: "Gold / Silver"},
  {id: "crystal", label: "Crystal"},
  {id: "ruby-sapphire", label: "Ruby / Sapphire"},
  {id: "emerald", label: "Emerald"},
  {id: "firered-leafgreen", label: "FireRed / LeafGreen"},
  {id: "diamond-pearl", label: "Diamond / Pearl"},
  {id: "platinum", label: "Platinum"},
  {id: "heartgold-soulsilver", label: "HeartGold / SoulSilver"},
  {id: "black-white", label: "Black / White"},
  {id: "black2-white2", label: "Black 2 / White 2"},
  {id: "x-y", label: "X / Y"},
  {id: "oras", label: "Omega Ruby / Alpha Sapphire"},
  {id: "sun-moon", label: "Sun / Moon"},
  {id: "usum", label: "Ultra Sun / Ultra Moon"},
  {id: "sword-shield", label: "Sword / Shield"},
  {id: "bdsp", label: "Brilliant Diamond / Shining Pearl"},
  {id: "scarlet-violet", label: "Scarlet / Violet"},
];
